"""Install and uninstall generated Chiyo tool entry points."""

import os
from pathlib import Path

from chiyo_cli.tool_resolver import ToolCommandError


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
BIN_DIR = os.path.join(REPO_ROOT, "bin")
CONFIG_PATH = "~/.config/chiyo-cli/config.toml"
TOOLS_CONFIG_PATH = "~/.config/chiyo-cli/tools.toml"
LEGACY_SHELL_HELPERS = {
    "gop": ["gop-select"],
    "proj": ["proj-select"],
}


def chiyo_config():
    from chiyo_cli.tool_config import load_chiyo_config

    return load_chiyo_config(config_path=CONFIG_PATH)


def enabled_tool_keys(config):
    from chiyo_cli.tool_resolver import enabled_tool_keys as resolver_enabled_tool_keys

    return resolver_enabled_tool_keys(config)


def resolve_tool_command(tool_command, enabled_only=True):
    from chiyo_cli.tool_resolver import resolve_tool_command as resolver_resolve_tool_command

    return resolver_resolve_tool_command(
        tool_command,
        enabled_only=enabled_only,
        config_path=CONFIG_PATH,
        tools_config_path=TOOLS_CONFIG_PATH,
    )


def wrapper_path(tool_command, config):
    return os.path.join(config["wrapper_dir"], tool_command)


def completion_path(tool_command, config):
    return os.path.join(config["completion_dir"], f"_{tool_command}")


def shell_path(tool_command, config):
    return os.path.join(config["shell_dir"], f"{tool_command}.zsh")


def helper_path(helper_command, config):
    return os.path.join(config["wrapper_dir"], helper_command)


def wrapper_script(tool_command):
    return "\n".join(
        [
            "#!/bin/sh",
            f'exec chiyo run {tool_command} "$@"',
            "",
        ]
    )


def shell_function_script(tool_command):
    return "\n".join(
        [
            f"# Generated by chiyo install {tool_command}",
            f"{tool_command}() {{",
            "  local chiyo_shell_code",
            f'  chiyo_shell_code="$(chiyo shell {tool_command} "$@")" || return',
            '  [ -n "$chiyo_shell_code" ] && eval "$chiyo_shell_code"',
            "}",
            "",
        ]
    )


def completion_script(tool_command):
    return "\n".join(
        [
            "#compdef " + tool_command,
            "",
            "local -a candidates",
            f'candidates=("${{(@f)$(chiyo run {tool_command} --list-completions 2>/dev/null)}}")',
            '_describe "candidates" candidates',
            "",
        ]
    )


def is_generated_wrapper(path, tool_command):
    expanded = os.path.expanduser(path)

    if not os.path.exists(expanded) or os.path.islink(expanded):
        return False

    try:
        content = Path(expanded).read_text(encoding="utf-8")
    except OSError:
        return False

    return content == wrapper_script(tool_command)


def is_generated_completion(path, tool_command):
    expanded = os.path.expanduser(path)

    if not os.path.exists(expanded) or os.path.islink(expanded):
        return False

    try:
        content = Path(expanded).read_text(encoding="utf-8")
    except OSError:
        return False

    return content == completion_script(tool_command)


def is_generated_shell_artifact(path, tool_command):
    expanded = os.path.expanduser(path)

    if not os.path.exists(expanded) or os.path.islink(expanded):
        return False

    try:
        content = Path(expanded).read_text(encoding="utf-8")
    except OSError:
        return False

    return content == shell_function_script(tool_command)


def write_wrapper(path, tool_command):
    expanded = os.path.expanduser(path)
    existing_is_safe = (
        not os.path.exists(expanded)
        or is_generated_wrapper(expanded, tool_command)
    )

    if not existing_is_safe:
        raise ToolCommandError(f"refusing to replace existing file: {expanded}")

    os.makedirs(os.path.dirname(expanded), exist_ok=True)
    temporary = f"{expanded}.tmp"
    Path(temporary).write_text(wrapper_script(tool_command), encoding="utf-8")
    os.chmod(temporary, 0o755)
    os.replace(temporary, expanded)
    return expanded


def write_shell_artifact(path, tool_command):
    expanded = os.path.expanduser(path)
    existing_is_safe = (
        not os.path.exists(expanded)
        or is_generated_shell_artifact(expanded, tool_command)
    )

    if not existing_is_safe:
        raise ToolCommandError(f"refusing to replace existing file: {expanded}")

    os.makedirs(os.path.dirname(expanded), exist_ok=True)
    temporary = f"{expanded}.tmp"
    Path(temporary).write_text(shell_function_script(tool_command), encoding="utf-8")
    os.replace(temporary, expanded)
    return expanded


def write_completion(path, tool_command):
    expanded = os.path.expanduser(path)
    existing_is_safe = (
        not os.path.exists(expanded)
        or is_generated_completion(expanded, tool_command)
    )

    if not existing_is_safe:
        raise ToolCommandError(f"refusing to replace existing file: {expanded}")

    os.makedirs(os.path.dirname(expanded), exist_ok=True)
    temporary = f"{expanded}.tmp"
    Path(temporary).write_text(completion_script(tool_command), encoding="utf-8")
    os.replace(temporary, expanded)
    return expanded


def remove_generated_wrapper(path, tool_command):
    expanded = os.path.expanduser(path)

    if not os.path.exists(expanded):
        return None

    if not is_generated_wrapper(expanded, tool_command):
        raise ToolCommandError(f"refusing to remove non-chiyo wrapper: {expanded}")

    os.unlink(expanded)
    return expanded


def assert_install_targets_are_safe(tool_command, config, shell_tool=False):
    wrapper = os.path.expanduser(wrapper_path(tool_command, config))
    completion = os.path.expanduser(completion_path(tool_command, config))

    if shell_tool:
        shell = os.path.expanduser(shell_path(tool_command, config))

        if os.path.exists(shell) and not is_generated_shell_artifact(shell, tool_command):
            raise ToolCommandError(f"refusing to replace existing file: {shell}")

        if os.path.exists(completion) and not is_generated_completion(completion, tool_command):
            raise ToolCommandError(f"refusing to replace existing file: {completion}")

        return

    if os.path.exists(wrapper) and not is_generated_wrapper(wrapper, tool_command):
        raise ToolCommandError(f"refusing to replace existing file: {wrapper}")

    if os.path.exists(completion) and not is_generated_completion(completion, tool_command):
        raise ToolCommandError(f"refusing to replace existing file: {completion}")


def resolve_install_target(tool_command):
    resolved = resolve_tool_command(tool_command, enabled_only=False)
    metadata = None if resolved is None else resolved[0]

    if metadata is None:
        raise ToolCommandError(f"unknown tool: {tool_command}")

    install_command = metadata.cmd if "/" in tool_command else tool_command
    return metadata, install_command


def install_resolved_tool_lines(metadata, install_command, config):
    if metadata.shell:
        removed_wrapper = remove_generated_wrapper(wrapper_path(install_command, config), install_command)
        installed_shell = write_shell_artifact(shell_path(install_command, config), install_command)
        installed_completion = write_completion(completion_path(install_command, config), install_command)
        lines = [
            f"installed {install_command} shell: {installed_shell}",
            f"installed _{install_command}: {installed_completion}",
        ]

        if removed_wrapper is not None:
            lines.append(f"removed old {install_command} wrapper: {removed_wrapper}")

        if metadata.key not in enabled_tool_keys(config):
            lines.append(f"warn    {metadata.key} installed but disabled for chiyo run")

        return lines

    installed_path = write_wrapper(wrapper_path(install_command, config), install_command)
    installed_completion = write_completion(completion_path(install_command, config), install_command)
    lines = [
        f"installed {install_command}: {installed_path}",
        f"installed _{install_command}: {installed_completion}",
    ]

    if metadata.key not in enabled_tool_keys(config):
        lines.append(f"warn    {metadata.key} installed but disabled for chiyo run")

    return lines


def install_tool_lines(tool_command):
    config = chiyo_config()
    metadata, install_command = resolve_install_target(tool_command)
    assert_install_targets_are_safe(install_command, config, shell_tool=metadata.shell)
    return install_resolved_tool_lines(metadata, install_command, config)


def install_tools_lines(tool_commands):
    config = chiyo_config()
    targets = [resolve_install_target(tool_command) for tool_command in tool_commands]
    seen = set()

    for metadata, install_command in targets:
        if install_command in seen:
            raise ToolCommandError(f"duplicate install target: {install_command}")

        seen.add(install_command)
        assert_install_targets_are_safe(install_command, config, shell_tool=metadata.shell)

    lines = []

    for metadata, install_command in targets:
        lines.extend(install_resolved_tool_lines(metadata, install_command, config))

    return lines


def uninstall_tool_lines(tool_command):
    config = chiyo_config()
    resolved = resolve_tool_command(tool_command, enabled_only=False)
    metadata = None if resolved is None else resolved[0]
    uninstall_command = metadata.cmd if metadata is not None and "/" in tool_command else tool_command
    path = os.path.expanduser(wrapper_path(uninstall_command, config))
    completion = os.path.expanduser(completion_path(uninstall_command, config))
    lines = []

    if metadata is not None and metadata.shell:
        shell = os.path.expanduser(shell_path(uninstall_command, config))

        if os.path.exists(shell):
            if not is_generated_shell_artifact(shell, uninstall_command):
                raise ToolCommandError(f"refusing to remove non-chiyo shell file: {shell}")

            os.unlink(shell)
            lines.append(f"uninstalled {uninstall_command} shell: {shell}")
        else:
            lines.append(f"not installed: {uninstall_command}")

        if os.path.exists(completion):
            if not is_generated_completion(completion, uninstall_command):
                raise ToolCommandError(
                    f"refusing to remove non-chiyo completion: {completion}"
                )

            os.unlink(completion)
            lines.append(f"uninstalled _{uninstall_command}: {completion}")

        for helper in LEGACY_SHELL_HELPERS.get(uninstall_command, []):
            helper_file = os.path.expanduser(helper_path(helper, config))
            source = os.path.join(BIN_DIR, helper)

            if os.path.islink(helper_file) and os.readlink(helper_file) == source:
                os.unlink(helper_file)
                lines.append(f"uninstalled {helper}: {helper_file}")

        return lines

    if os.path.exists(path):
        if not is_generated_wrapper(path, uninstall_command):
            raise ToolCommandError(f"refusing to remove non-chiyo wrapper: {path}")

        os.unlink(path)
        lines.append(f"uninstalled {uninstall_command}: {path}")
    else:
        lines.append(f"not installed: {uninstall_command}")

    if os.path.exists(completion):
        if not is_generated_completion(completion, uninstall_command):
            raise ToolCommandError(
                f"refusing to remove non-chiyo completion: {completion}"
            )

        os.unlink(completion)
        lines.append(f"uninstalled _{uninstall_command}: {completion}")

    return lines


def uninstall_tools_lines(tool_commands):
    targets = []
    seen = set()

    for tool_command in tool_commands:
        resolved = resolve_tool_command(tool_command, enabled_only=False)
        metadata = None if resolved is None else resolved[0]
        uninstall_command = metadata.cmd if metadata is not None and "/" in tool_command else tool_command

        if uninstall_command in seen:
            raise ToolCommandError(f"duplicate uninstall target: {uninstall_command}")

        seen.add(uninstall_command)
        targets.append(tool_command)

    lines = []

    for tool_command in targets:
        lines.extend(uninstall_tool_lines(tool_command))

    return lines
